DinamicDataMvc/Models/Metadata/BranchModel.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel.DataAnnotations;

namespace DinamicDataMvc.Models
{
    public class BranchModel
    {
        [BsonRequired]
        [BsonElement("Id")]
        [Display(Name = "Id")]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BsonElement("Code")]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [BsonElement("Description")]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

DinamicDataMvc/Models/Metadata/MetadataModel.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DinamicDataMvc.Models.Metadata
{
    [BsonIgnoreExtraElements]
    public class MetadataModel
    {
        [BsonId]
        [BsonRequired]
        [BsonElement("Id")]
        [Display(Name = "ID")]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BindProperty]
        [BsonRequired]
        [BsonElement("Name")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [BindProperty]
        [BsonRequired]
        [BsonElement("Version")]
        [Display(Name = "Version")]
        public int Version { get; set; }

        [BindProperty]
        [BsonElement("Date")]
        [Display(Name = "Date")]
        [BsonRepresentation(BsonType.DateTime)]
        public DateTime Date { get; set; }

        [BindProperty]
        [BsonElement("State")]
        [Display(Name = "State")]
        public string State { get; set; }

        [BindProperty]
        [Required]
        [BsonElement("Field")]
        [Display(Name = "Field")]
        public List<string> Field { get; set; }

        [BindProperty]
        [BsonElement("Branch")]
        [Display(Name = "Branch")]
        public List<string> Branch { get; set; }
    }
}

DinamicDataMvc/Models/Metadata/StateModel.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel.DataAnnotations;

namespace DinamicDataMvc.Models
{
    public class StateModel
    {
        [BsonRequired]
        [BsonElement("Id")]
        [Display(Name = "Id")]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BsonElement("Value")]
        [Display(Name = "Active")]
        public bool Value { get; set; }

        [BsonElement("Description")]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

DinamicDataMvc/Models/Metadata/ViewMetadataModel.cs
using System.ComponentModel;

namespace DinamicDataMvc.Models.Metadata
{
    public class ViewMetadataModel
    {
        [DisplayName("Id")]
        public string Id { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Version")]
        public string Version { get; set; }

        [DisplayName("Creation Date")]
        public string Date { get; set; }

        [DisplayName("Branch")]
        public string Branch { get; set; }

        [DisplayName("Current State")]
        public string State { get; set; }
    }
}

DinamicDataMvc/Controllers/Metadata/MetadataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DinamicDataMvc.Interfaces;
using DinamicDataMvc.Models.Metadata;
using DinamicDataMvc.Models.Field;
using DinamicDataMvc.Models.Process;
using Microsoft.AspNetCore.Mvc;
using DinamicDataMvc.Models.Properties;

namespace DinamicDataMvc.Controllers.Metadata
{
    public class MetadataController : Controller
    {
        private readonly IConnectionManagementService _Connection;
        private readonly IMetadataService _Metadata;
        private readonly IBranchService _GetBranchById;
        private readonly IStateService _GetStateById;
        private readonly IFieldService _Field;
        private readonly IPaginationService _SetPagination;
        private readonly IKeyGenerates _KeyID;
        private readonly IPropertyService _Properties;
        private readonly IValidationService _Validation;
        private readonly IProcessHistory _Log;

        public MetadataController(IConnectionManagementService Connection, IMetadataService GetMetadata, IBranchService GetBranchById, IStateService GetStateById, IFieldService GetFieldTypes, IPaginationService SetPagination, IKeyGenerates KeyID, IPropertyService Properties, IValidationService Validation, IProcessHistory Log)
        {
            _Connection = Connection;
            _Metadata = GetMetadata;
            _GetBranchById = GetBranchById;
            _GetStateById = GetStateById;
            _Field = GetFieldTypes;
            _SetPagination = SetPagination;
            _KeyID = KeyID;
            _Properties = Properties;
            _Validation = Validation;
            _Log = Log;
        }

        /*
         * Read Action - Implementa a lista de Processos ao nivel dos seus Metadados;
         */
        [HttpGet("/Metadata/Read/")]
        public async Task<ActionResult> Read()
        {
            //Stores data in cache;
            TempData["Name"] = Request.Query["Name"];
            string searchName = TempData["Name"].ToString();
            ViewBag.Name = searchName;

            TempData["Version"] = Request.Query["Version"];
            string searchVersion = TempData["Version"].ToString();
            ViewBag.Version = searchVersion;

            string pageNumber = Request.Query["Page"];
            
            if (string.IsNullOrEmpty(pageNumber))
            {
                pageNumber = 1.ToString();
            }

            int pageIndex = Convert.ToInt32(pageNumber);

            if (string.IsNullOrEmpty(searchName))
            {
                searchName = null;
            }
            //No caso de a string que representa a informação do filtro de pesquisa por versão, ser nula ou vazia,
            //define-se como valor default a versão 1;
            if (string.IsNullOrEmpty(searchVersion))
            {
                searchVersion = null;
            }

            ViewBag.PageNumber = pageNumber;

            _Connection.DatabaseConnection();
            _Metadata.SetDatabase(_Connection.GetDatabase()); //Estabeleçe a conexão;
            _GetBranchById.SetDatabase(_Connection.GetDatabase());
            _GetStateById.SetDatabase(_Connection.GetDatabase());

            _Metadata.SetFilterParameters(searchName, searchVersion);
            _Metadata.ReadFromDatabase();

            List<MetadataModel> metadataList = _Metadata.GetProcessesMetadataList();
            List<ViewMetadataModel> viewModels = new List<ViewMetadataModel>();

            if(metadataList != null)
            {
                foreach (var metadata in metadataList)
                {
                    _GetBranchById.ReadFromDatabase(metadata.Branch);
                    _GetStateById.ReadFromDatabase(metadata.State);

                    ViewMetadataModel viewModel = new ViewMetadataModel()
                    {
                        Id = metadata.Id,
                        Name = metadata.Name,
                        Version = metadata.Version.ToString(),
                        Date = metadata.Date.ToString(),
                        Branch = _GetBranchById.GetBranches(),
                        State = _GetStateById.GetStateDescription()
                    };

                    viewModels.Add(viewModel);
                }
            }
            _SetPagination.SetNumberOfModelsByPage(4);
            Dictionary<int, List<ViewMetadataModel>> modelsToDisplay = _SetPagination.SetModelsByPage(viewModels);

            int NumberOfPages = modelsToDisplay.Count();
            ViewBag.NumberOfPages = NumberOfPages;


            //Se a base de dados não tiver processos armazenados para mostrar na listagem de processos;
            if(modelsToDisplay.Count() == 0)
            {
                List<ViewMetadataModel> models = new List<ViewMetadataModel>();
                ViewMetadataModel model = new ViewMetadataModel()
                {
                    Id = string.Empty,
                    Name = string.Empty,
                    Version = string.Empty,
                    Date = string.Empty,
                    Branch = string.Empty,
                    State = string.Empty
                };
                models.Add(model);
                return await Task.Run(() => View("Read", models));
            }

            return await Task.Run(() => View("Read", modelsToDisplay[pageIndex]));
        }


        [HttpGet("/Metadata/GetDetailsByName")]
        public async Task<ActionResult> GetDetailsByName(string name)
        {
            if (name == null)
            {
                return BadRequest();
            }

            //------------------------------------------
            //Add - Pagination to Page (Phase 1)
            //------------------------------------------
            string pageNumber = Request.Query["Page"];
            if (string.IsNullOrEmpty(pageNumber))
            {
                pageNumber = 1.ToString();
            }
            int pageIndex = Convert.ToInt32(pageNumber);
            ViewBag.PageNumber = pageNumber;
            //------------------------------------------

            _Connection.DatabaseConnection();
            _Metadata.SetDatabase(_Connection.GetDatabase());
            _GetBranchById.SetDatabase(_Connection.GetDatabase());
            _GetStateById.SetDatabase(_Connection.GetDatabase());

            List<MetadataModel> modelList = _Metadata.GetProcessByName(name);
            List<ViewMetadataModel> _ViewModelList = new List<ViewMetadataModel>();

            ViewBag.Name = modelList[0].Name; //Stores the process name;

            foreach (var model in modelList)
            {
                _GetBranchById.ReadFromDatabase(model.Branch);
                _GetStateById.ReadFromDatabase(model.State);
                ViewMetadataModel _details = new ViewMetadataModel()
                {
                    Id = model.Id,
                    Name = model.Name,
                    Version = model.Version.ToString(),
                    Date = model.Date.ToString(),
                    Branch = _GetBranchById.GetBranches(),
                    State = _GetStateById.GetStateDescription(),
                };
                _ViewModelList.Add(_details);
            }

            //------------------------------------------
            //Add - Pagination to Page (Phase 2)
            //------------------------------------------
            _SetPagination.SetNumberOfModelsByPage(2);
            Dictionary<int, List<ViewMetadataModel>> modelsToDisplay = _SetPagination.SetModelsByPage(_ViewModelList);
            int NumberOfPages = modelsToDisplay.Count();
            ViewBag.NumberOfPages = NumberOfPages;
            //------------------------------------------
            return await Task.Run(() => View("GetDetailsByName", modelsToDisplay[pageIndex]));
        }


        [HttpGet("/Metadata/GetDetailsByVersion")]
        public async Task<ActionResult> GetDetailsByVersion(string id)
        {
            _Connection.DatabaseConnection(); //Estabeleçe-se a conexão com a base de dados;
            _Metadata.SetDatabase(_Connection.GetDatabase()); //Cria uma instância da base de dados no serviço;
            _Field.SetDatabase(_Connection.GetDatabase()); //Cria uma instância da base de dados no serviço;

            //Se o identificador não tiver qualquer valor armazenado, devolve um bad request;
            if(id == null)
            {
                return BadRequest();
            }

            //------------------------------------------
            //Add - Pagination to Page (Phase 1)
            //------------------------------------------
            string pageNumber = Request.Query["Page"];
            if (string.IsNullOrEmpty(pageNumber))
            {
                pageNumber = 1.ToString();
            }
            int pageIndex = Convert.ToInt32(pageNumber);
            ViewBag.PageNumber = pageNumber; //Passa para a view o número da página;
            ViewBag.Id = id; //Passa para a view o identificador do processo;
            //------------------------------------------

            //1º Passo - obter o MetadataModel;
            MetadataModel metadata = _Metadata.GetMetadata(id);

            //2ºPasso - Coverter o Id do estado para a sua descrição;
            _GetStateById.ReadFromDatabase(metadata.State); 
            ViewBag.State = _GetStateById.GetStateDescription();

            //3ºPasso - Agregar oas descrições dos branches ao qual o processo pertence numa string;
            _GetBranchById.ReadFromDatabase(metadata.Branch);
            ViewBag.Branches = _GetBranchById.GetBranches();

            //4º Passo - obter o(s) FieldModel(s);
            List<FieldModel> fields = new List<FieldModel>();

            foreach(var fieldId in metadata.Field)
            {
                FieldModel field = _Field.GetField(fieldId);
                fields.Add(field);
            }

            //------------------------------------------

DinamicDataMvc/Views/Metadata/Create.cshtml
@model DinamicDataMvc.Models.Metadata.MetadataModel
@{
    ViewData["Title"] = "Create";
    var CurrentDate = DateTime.Now.ToLocalTime().ToString();

    //Display an alert message if the Process Name already exists in the database;
    if (TempData["AlertMessage"] != null)
    {
        <script type="text/javascript">
                window.alert(@Html.Raw(Json.Serialize(TempData["AlertMessage"])));
        </script>
    }
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body style="background-color:ghostwhite">
    <hr />
    <div class="container" id="subtitleDiv">
        <h2 id="ProcessDescription">Create New Form</h2>
    </div>
    <hr />
    <div class="row justify-content-lg-center" style="border:none; margin-left:15px; margin-right:15px;">
        @using (Html.BeginForm("CreateProcess", "Metadata", FormMethod.Post, new { @width = "60%" }))
        {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"><b>Form Name</b></label>
                <input asp-for="Name" class="form-control" type="text" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Version" class="control-label"><b>Form Version</b></label>
                <input asp-for="Version" class="form-control" type="text" readonly value="0" />
                <span asp-validation-for="Version" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Branch" class="control-label"><b>Branch</b></label>
                <div class="row">
                    <div class="columns" style="padding-left:25px;">
                        <label><b><i>Development</i></b></label>
                        <input type="checkbox" class="form-control" name="branch" value="Dev" checked />
                    </div>
                    <div class="columns" style="padding-left:25px;">
                        <label><b><i>Quality</i></b></label>
                        <input type="checkbox" class="form-control" name="branch" value="Qa" />
                    </div>
                    <div class="columns" style="padding-left:25px;">
                        <label><b><i>Production</i></b></label>
                        <input type="checkbox" class="form-control" name="branch" value="Prod" />
                    </div>
                </div>
                <span asp-validation-for="Branch" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Date" class="form-control" type="hidden" value="@CurrentDate" readonly size="10" />
            </div>
            <div class="form-group">
                <input asp-for="State" class="form-control" type="hidden" readonly="readonly" value="Inactive" size="10" />
            </div>
            <div class="button-group" style="margin-top:50px; margin-left:70px;">
                <button type="reset"><i class="fa fa-eraser"></i> Clear </button>
                <button type="submit"><i class="fa fa-plus"> Fields </i></button>
            </div>
        }
    </div>
    <br />
    <hr />
    <div class="row justify-content-lg-center">
        @using (Html.BeginForm("Read", "Metadata", FormMethod.Get))
        {
            <button type="submit"><i class="fa fa-close"></i> Cancel </button>
        }
    </div>
</body>

DinamicDataMvc/Views/Metadata/Delete.cshtml
@model DinamicDataMvc.Models.Metadata.ViewMetadataModel
@{
    ViewData["Title"] = "Delete";
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/ListPageStyle.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body>
    <hr />
    <div class="container" id="subtitleDiv">
        <h2 id="ProcessDescription">Are you sure you want to delete this process?</h2>
    </div>
    <hr />
    <div class="container">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Version)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Version)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Branch)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Branch)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.State)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.State)
            </dd>
        </dl>
    </div>
    <hr />
    <div class="container">
        <div class="btn-group">
            @using (Html.BeginForm("Confirm", "Metadata", new { ID = Model.Id }, FormMethod.Post))
            {
                <button type="submit" onclick=""><i class="fa fa-check"></i> Yes </button>
            }
            
            @using (Html.BeginForm("Read", "Metadata", FormMethod.Get, new { style = "padding-left:10px"}))
            {
                <button type="submit"><i class="fa fa-close"></i> No </button>
            }
        </div>
    </div>
</body>

DinamicDataMvc/Views/Metadata/GetDetailsByName.cshtml
@model IEnumerable<DinamicDataMvc.Models.Metadata.ViewMetadataModel>
@{
    ViewData["Title"] = "Details By Process Name";
    var pageNumber = ViewBag.NumberOfPages;
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body>
    <hr />
    <div class="container" id="subtitleDiv">
        <h2 id="ProcessDescription">@Html.ViewBag.Name Versions</h2>
    </div>
    <hr />
    <div class="container" id="linkDiv">
        <a id="updateLink" href="/Metadata/Update?ProcessName=@Html.ViewBag.Name"><i class="fa fa-database"></i> Update Form </a>
    </div>
    <hr />
    <div class="container">
        <div class="table-responsive table-striped">
            <table class="table table-bordered" border="1" id="processResultTable">
                <thead>
                    <tr id="tableHeader">
                        <th>
                            @Html.DisplayNameFor(model => model.Version)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Branch)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.State)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="tableBody">
                            <td>
                                @Html.ActionLink(@Html.DisplayTextFor(modelItem => item.Version), "GetDetailsByVersion", "Metadata", new { ID = item.Id }, new { @class = "processDetails" })
                            </td>
                            <td>
                                @Html.DisplayTextFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayTextFor(modelItem => item.Branch)
                            </td>
                            <td>
                                @Html.DisplayTextFor(modelItem => item.State)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <ul class="pagination pagination-sm">
            @for (int i = 1; i <= Convert.ToInt32(pageNumber); i++)
            {
                <li class="page-item"><a class="page-link" style="color:#212529;" href="/Metadata/GetDetailsByName?Name=@Html.ViewBag.Name&Page=@i"><b>@i</b></a></li>
            }
        </ul>
    </div>
    <hr />
    <div class="container">
        @using (Html.BeginForm("Read", "Metadata", FormMethod.Get))
        {
            <button><i class="fa fa-list"></i> Back to List </button>
        }
    </div>
</body>

DinamicDataMvc/Views/Metadata/GetDetailsByVersion.cshtml
@model DinamicDataMvc.Models.Process.ViewProcessModel
@{
    ViewData["Title"] = "ByVersion";
    var pageNumber = ViewBag.NumberOfPages;
    var processId = ViewBag.Id;

    bool[] branchesState = new bool[3] { false, false, false };

    string[] branchList = ViewBag.Branches.Split(" ");

    foreach (var description in branchList)
    {
        if (description.Equals("Development"))
        {
            branchesState[0] = true;
        }
        else if (description.Equals("Quality"))
        {
            branchesState[1] = true;
        }
        else if (description.Equals("Production"))
        {
            branchesState[2] = true;
        }
    }
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body>
    <hr />
    <div class="container" id="subtitleDiv">
        <h2 id="ProcessDescription">@Model.Metadata.Name Version @Model.Metadata.Version.ToString()</h2>
    </div>
    <hr />
    <div class="container" id="processDetails">
        <span>
            <label>Creation Date: <strong> @Model.Metadata.Date.ToString().Substring(0, 10) </strong></label>
            <label>Branches: </label>
            <strong>@Html.Label("Development ")</strong>
            @Html.CheckBox("Development", @branchesState[0], new { @disabled = "disabled" })
            <strong>@Html.Label("Quality ")</strong>
            @Html.CheckBox("Quality", @branchesState[1], new { @disabled = "disabled" })
            <strong>@Html.Label("Production ")</strong>
            @Html.CheckBox("Production", @branchesState[2], new { @disabled = "disabled" })
            <label>State: <strong> @ViewBag.State </strong></label>
        </span>
    </div>
    <hr />
    <div class="container" id="fieldDiv">
        <h2 id="FieldDescription"> Form Fields </h2>
    </div>
    <hr />
    <div class="container">
        <div class="table-responsive table-striped">
            <table class="table table-bordered" border="1" style="border-style:dotted">
                <thead>
                    <tr id="tableHeader">
                        <th>
                            @Html.DisplayNameFor(model => model.Fields.ElementAt(0).Type)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Fields.ElementAt(0).Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Fields.ElementAt(0).Date)
                        </th>
                        <th>
                            @Html.DisplayName("Properties")
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Fields.Count; i++)
                    {
                        <tr id="tableBody">
                            <td>
                                <b>@Html.DisplayFor(modelItem => Model.Fields.ElementAt(i).Type)</b>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Fields.ElementAt(i).Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Fields.ElementAt(i).Date)
                            </td>
                            <td align="center">
                                @using (Html.BeginForm("Details", "Properties", new { PropertiesId = Model.Fields.ElementAt(i).Properties, ProcessName = Model.Metadata.Name, ProcessVersion = Model.Metadata.Version.ToString(), FieldType = Model.Fields.ElementAt(i).Type, FieldName = Model.Fields.ElementAt(i).Name }, FormMethod.Post))
                                {
                                    <button type="submit" id="@i"><i class="fa fa-cog"></i></button>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <ul class="pagination pagination-sm">
            @for (int i = 1; i <= Convert.ToInt32(pageNumber); i++)
            {
                <li class="page-item"><a class="page-link" style="color:#212529;" href="/Metadata/GetDetailsByVersion?ID=@processId&Page=@i"><b>@i</b></a></li>
            }
        </ul>
    </div>
    <hr />
    <div class="container">
        <div class="btn-group">
            <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"></i> Go Back </button>
            @using (Html.BeginForm("Read", "Metadata", FormMethod.Get, new { style = "padding-left:10px" }))
            {
                <button type="submit"><i class="fa fa-list"></i> Back to List </button>
            }
        </div>
    </div>
</body>

DinamicDataMvc/Views/Metadata/WebFormGenerator.cshtml
@{
    ViewData["Title"] = "WebFormGenerator";
    
    string template = ViewBag.Template;

    string[] htmlElements = template.Split("|");
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body style="background-color:ghostwhite">
    <hr />
    <div class="container" id="subtitleDiv">
        <h2> Generated Web Form </h2>
    </div>
    <hr />
    <div class="container">
        @for (int i = 0; i < htmlElements.Length; i++)
        {
            @Html.Raw(htmlElements.ElementAt(i))
            @Html.Raw("<br />")
        }
    </div>
    <hr />
    <div class="container">
        <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"> Go Back </i></button>
    </div>
</body>