DinamicDataMvc/Models/Tools/CollectionModel.cs
using System.Collections.Generic;


namespace DinamicDataMvc.Models.Tools
{
    public class CollectionModel
    {
        public List<string> CollectionNames { get; set; }

        public List<long> NumberOfDocuments { get; set; }
    }
}

DinamicDataMvc/Models/Tools/WebFormModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DinamicDataMvc.Models.Tools
{
    public class WebFormModel
    {
        [BindProperty]
        public string Type { get; set; }

        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public string Size { get; set; }

        [BindProperty]
        public string Value { get; set; }

        [BindProperty]
        public string Maxlength { get; set; }

        [BindProperty]
        public string Required { get; set; }

        [BindProperty]
        public bool Readonly { get; set; }
    }
}

DinamicDataMvc/Controllers/Tools/ToolsController.cs
using DinamicDataMvc.Interfaces;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using System.Collections.Generic;
using System.Threading.Tasks;
using DinamicDataMvc.Models.Tools;
using DinamicDataMvc.Models.Field;
using DinamicDataMvc.Models.Metadata;
using DinamicDataMvc.Models.Data;
using DinamicDataMvc.Models.Log;
using DinamicDataMvc.Models.Config;
using DinamicDataMvc.Models.Properties;

namespace DinamicDataMvc.Controllers.Tools
{
    /*
     * Controlador para controlo de funcionalidades do sistema;
     */
    public class ToolsController : Controller
    {
        private readonly IConnectionManagementService _Connection;
        private readonly IMetadataService _Metadata;
        private readonly IBranchService _Branch;
        private readonly IStateService _State;
        private readonly IKeyGenerates _KeyId;
        private readonly IMessage _Message;
        private readonly IProcessHistory _Log;
        private readonly IFieldService _Field;
        private readonly IPropertyService _Property;

        public ToolsController(IConnectionManagementService Connection, IMetadataService Metadata, IBranchService Branch, IStateService State, IKeyGenerates KeyId, IMessage Message, IProcessHistory Log, IFieldService Field, IPropertyService Property)
        {
            _Connection = Connection;
            _Metadata = Metadata;
            _Branch = Branch;
            _State = State;
            _KeyId = KeyId;
            _Message = Message;
            _Log = Log;
            _Field = Field;
            _Property = Property;
        }


        [HttpGet("/Tools/Dasboard/")]
        public async Task<ActionResult> Dashboard()
        {
            return await Task.Run(() => View("Dashboard"));
        }


        [HttpGet("/Tools/GetAllCollections/")]
        public async Task<ActionResult> GetAllCollections()
        {
            _Connection.DatabaseConnection();
            var database = _Connection.GetDatabase();

            Dictionary<string, long> map = new Dictionary<string, long>()
            {
                { "Field", await database.GetCollection<FieldModel>("Field").Find(s => true).CountDocumentsAsync()},
                { "Metadata", await database.GetCollection<MetadataModel>("Metadata").Find(s => true).CountDocumentsAsync()},
                { "Branch", await database.GetCollection<BranchModel>("Branch").Find(s => true).CountDocumentsAsync()},
                { "State", await database.GetCollection<StateModel>("State").Find(s => true).CountDocumentsAsync()},
                { "Properties", await database.GetCollection<PropertiesModel>("Properties").Find(s => true).CountDocumentsAsync()},
                { "History", await database.GetCollection<ViewDataModel>("History").Find(s => true).CountDocumentsAsync()},
                { "Data", await database.GetCollection<ViewDataModel>("Data").Find(s => true).CountDocumentsAsync()}
            };

            List<string> _CollectionNames = database.ListCollectionNames().ToList();
            List<long> _NumberOfDocuments = new List<long>();

            foreach (string name in _CollectionNames)
            {
                long NumberOfDocuments = map[name];
                _NumberOfDocuments.Add(NumberOfDocuments);
            }

            CollectionModel model = new CollectionModel()
            {
                CollectionNames = _CollectionNames,
                NumberOfDocuments = _NumberOfDocuments
            };

            return await Task.Run(() => View("GetAllCollections", model));
        }


        [HttpGet("/Tools/ConnectionInfo/")]
        public async Task<ActionResult> ConnectionInfo()
        {
            _Connection.DatabaseConnection();
            IMongoDatabase database = _Connection.GetDatabase();

            ViewBag.Database = database.DatabaseNamespace.DatabaseName;
            string serverConnectionInfo = _Connection.GetConnectionString();

            ViewBag.Connection = serverConnectionInfo;

            return await Task.Run(() => View("ConnectionInfo"));
        }


        [HttpGet("/Tools/PopulateStateCollection")]
        public async Task<ActionResult> PopulateStateCollection()
        {
            _Connection.DatabaseConnection();
            var database = _Connection.GetDatabase();
            _State.SetDatabase(database);
            long documentNumber = await database.GetCollection<StateModel>("State").Find(s => true).CountDocumentsAsync();

            ViewBag.Message = _Message.GetMessage(2);
            ViewBag.EmptyCollection = "false";

            if (documentNumber == 0)
            {
                List<StateModel> stateModels = new List<StateModel>();
                _KeyId.SetKey();
                StateModel active = new StateModel()
                {
                    Id = _KeyId.GetKey(),
                    Value = true,
                    Description = "Active"
                };
                stateModels.Add(active);

                _KeyId.SetKey();
                StateModel inactive = new StateModel()
                {
                    Id = _KeyId.GetKey(),
                    Value = false,
                    Description = "Inactive"
                };
                stateModels.Add(inactive);

                _State.CreateState(stateModels);

                ViewBag.Message = _Message.GetMessage(4);
                ViewBag.EmptyCollection = "true";
            }

            List<StateModel> states = _State.GetStateModels();

            return await Task.Run(() => View("PopulateStateCollection", states));
        }


        [HttpGet("/Tools/PopulateBranchCollection")]
        public async Task<ActionResult> PopulateBranchCollection()
        {
            _Connection.DatabaseConnection();
            var database = _Connection.GetDatabase();
            _Branch.SetDatabase(database);
            long documentNumber = await database.GetCollection<BranchModel>("Branch").Find(s => true).CountDocumentsAsync();

            ViewBag.Message = _Message.GetMessage(1);
            ViewBag.EmptyCollection = "false";

            if (documentNumber == 0)
            {
                List<BranchModel> branchModels = new List<BranchModel>();
                _KeyId.SetKey();
                BranchModel dev = new BranchModel()
                {
                    Id = _KeyId.GetKey(),
                    Code = "Dev",
                    Description = "Development"
                };
                branchModels.Add(dev);

                _KeyId.SetKey();
                BranchModel qa = new BranchModel()
                {
                    Id = _KeyId.GetKey(),
                    Code = "Qa",
                    Description = "Quality"
                };
                branchModels.Add(qa);

                _KeyId.SetKey();
                BranchModel prod = new BranchModel()
                {
                    Id = _KeyId.GetKey(),
                    Code = "Prod",
                    Description = "Production"
                };
                branchModels.Add(prod);

                _Branch.CreateBranch(branchModels);
                ViewBag.Message = _Message.GetMessage(3);
                ViewBag.EmptyCollection = "true";
            }

            List<BranchModel> branches = _Branch.GetBranchModels(); //Obter todos os branch models armazenados na colecção Branch;

            return await Task.Run(() => View("PopulateBranchCollection", branches));
        }


        [HttpPost("/Tools/WebFormGenerator/")]
        public async Task<ActionResult> WebFormGenerator()
        {
            ViewBag.Fragment1 = "<div class='container'><h1>Login Page</h1></div>";
            ViewBag.Fragment2 = "<div class='container'><label><b>Username</b></label><br /><input type='email' value='123456@email.com' size='25' maxlength='20' name='email_22 /></div><br />";
            ViewBag.Fragment3 = "<div class='container'><button type='submit'> Login </button></div>";
            return await Task.Run(() => View("WebFormGenerator"));
        }


        [HttpGet("/Tools/GetProcessLogs/")]
        public async Task<ActionResult> GetProcessLogs()
        {
            _Connection.DatabaseConnection();
            var database = _Connection.GetDatabase();
            _Log.SetDatabase(database);
            List<LogModel> logs = _Log.GetProcessesLogs();

            return await Task.Run(() => View("GetProcessLogs", logs));
        }
    }
}

DinamicDataMvc/Views/Tools/ConnectionInfo.cshtml
@{
    ViewData["Title"] = "ConnectionInfo";
    string database = ViewBag.Database;
    string serverConn = ViewBag.Connection;
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <style>
        body {
            background-color: ghostwhite;
        }

        div {
            display: block;
        }

        .column {
            width: 50.00%;
            height: 50.00%;
            text-align: center;
            color: #000000;
            font-family: Arial, Helvetica, sans-serif;
            font-size: larger;
            margin-left: 10px;
            padding: 5px;
        }

        img {
            max-width: 65.00%;
            max-height: 50.00%;
        }
    </style>
</head>
<body>
    <div row>
        <div class="column">
            <img src="~/images/ConnectionInfoLogo.png" />
        </div>
        <div class="column">
            <p>Current database is:<b>@database</b></p>
            <p>Server is running at: <b>@serverConn.Substring(10, 15)</b></p>
        </div>
    </div>
    <div class="container">
        <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"> Go Back </i></button>
    </div>
</body>

DinamicDataMvc/Views/Tools/CreateWebForm.cshtml
@{
    ViewData["Title"] = "CreateWebForm";

    string template = ViewBag.Template;

    string[] htmlElements = template.Split("|");
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body style="background-color:ghostwhite">
    <hr />
    <div class="container" id="subtitleDiv">
        <h2> Generated Web Form </h2>
    </div>
    <hr />
    <div class="container">
        @for(int i = 0; i < htmlElements.Length; i++)
        {
            @Html.Raw(htmlElements.ElementAt(i))
            @Html.Raw("<br />")
        }
    </div>
</body>

DinamicDataMvc/Views/Tools/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        .column {
            background-color: darkorange; 
            width:33.33%; 
            height:50.00%;
            text-align: center;
            color:ghostwhite;
            font-family:Arial, Helvetica, sans-serif;
            font-size:large;
        }
        .panel {
            max-width:50.00%; 
            max-height:50.00%;
        }
    </style>
</head>
<body>
    <div class="row">
        <div class="column">
            <form asp-action="GetAllCollections" asp-controller="Tools" method="get">
                <label>List all Collections</label>
                <button type="submit"><img src="~/images/Configuration.png" alt="Create Collection" class="panel"/></button>
            </form>
        </div>
        <div class="column">
            <form asp-action="PopulateBranchCollection" asp-controller="Tools" method="get">
                <label>Create Branch Collection</label>
                <button type="submit"><img src="~/images/CreateBranch.png" alt="Create Branch Collection" class="panel" /></button>
            </form>
        </div>
        <div class="column">
            <form asp-action="PopulateStateCollection" asp-controller="tools" method="get">
                <label>Create State Collection</label>
                <button type="submit"><img src="~/images/CreateState.png" alt="Create State Collection" class="panel" /></button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <form asp-action="ConnectionInfo" asp-controller="Tools" method="get">
                <label>Database Information</label>
                <button type="submit"><img src="~/images/DatabaseInfo.png" alt="Database Info" class="panel" /></button>
            </form>
        </div>
        <div class="column">
            <form asp-action="WebFormGenerator" asp-controller="Tools" method="post">
                <label>Web Form Generator</label>
                <button type="submit"><img src="~/images/WebForm.png" alt="Web Form Generator" class="panel" /></button>
            </form>
        </div>
        <div class="column">
            <form asp-action="GetProcessLogs" asp-controller="Tools" method="get">
                <label>Processes Logs</label>
                <button type="submit"><img src="~/images/History.png" alt="Processes Logs" class="panel" /></button>
            </form>
        </div>
    </div>
</body>

DinamicDataMvc/Views/Tools/GetAllCollections.cshtml
@model DinamicDataMvc.Models.Tools.CollectionModel
@{
    ViewData["Title"] = "GetAllCollections";
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body>
    <hr />
    <div class="container" id="subtitleDiv">
        <h2 id="ProcessDescription">Collections</h2>
    </div>
    <hr />
    <div class="container">
        <div class="table-responsive table-striped">
            <table class="table table-bordered" border="1" style="border-style:dotted">
                <thead>
                    <tr style="background-color:#212529; color:white;">
                        <td>
                            @Html.DisplayName("Collection Names")
                        </td>
                        <td>
                            @Html.DisplayName("Number of Documents")
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.CollectionNames.Count(); i++)
                    {
                        <tr>
                            <td>
                                <strong><i>@Model.CollectionNames.ElementAt(i)</i></strong>
                            </td>
                            <td>
                                <strong><i>@Model.NumberOfDocuments.ElementAt(i)</i></strong>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"> Go Back </i></button>
    </div>
</body>

DinamicDataMvc/Views/Tools/GetProcessLogs.cshtml
@model IEnumerable<DinamicDataMvc.Models.Log.LogModel>

@{
    ViewData["Title"] = "GetProcessLogs";
}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>
<body style="background-color:ghostwhite">
    <hr />
    <div class="container" id="subtitleDiv">
        <h2 id="ProcessDescription">Processes Logs</h2>
    </div>
    <hr />
    <div class="container">
        <div class="table-responsive table-striped">
            <table class="table table-bordered" border="1" id="processResultTable">
                <thead>
                    <tr id="tableHeader">
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProcessId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProcessName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ProcessVersion)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Operation)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.RegisterDateTime)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="tableBody">
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProcessId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProcessName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProcessVersion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Operation)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RegisterDateTime)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <br />
    <div class="container">
        <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"> Go Back </i></button>
    </div>
</body>

DinamicDataMvc/Views/Tools/PopulateBranchCollection.cshtml
@model IEnumerable<DinamicDataMvc.Models.Config.BranchModel>
@{
    ViewData["Title"] = "PopulateBranchCollection";
    var message = ViewBag.Message;
    var collectionIsEmpty = ViewBag.EmptyCollection;
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
    <style>
        #sucess {
            color:green; 
            text-align:end;
        }

        #fail {
            color:red; 
            text-align:end;
        }

        .infoMessage {
            font-family: Arial, Helvetica, sans-serif;
            font-size: large;
            font-display:auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="subtitleDiv">
            <h2 id="ProcessDescription"> Branch Collection Info </h2>
        </div>
        
        @if (collectionIsEmpty.Equals("true"))
        {
            <p class="infoMessage" id="sucess"><strong>@message</strong></p>
        }
        @if (collectionIsEmpty.Equals("false"))
        {
            <p class="infoMessage" id="fail"><strong>@message</strong></p>
        }
    </div>
    <div class="container">
        <div class="table-responsive table-striped">
            <table class="table table-bordered" border="1" id="processResultTable">
                <thead>
                    <tr id="tableHeader">
                        <th>
                            @Html.DisplayName("Branch Order Number")
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Code)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 1; i <= Model.Count(); i++)
                    {
                        <tr id="tableBody">
                            <td>
                                #_@i
                            </td>
                            <td>
                                @Html.DisplayFor(modelIndex => Model.ElementAt(i - 1).Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelIndex => Model.ElementAt(i - 1).Description)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"> Go Back </i></button>
    </div>
</body>

DinamicDataMvc/Views/Tools/PopulateStateCollection.cshtml
@model IEnumerable<DinamicDataMvc.Models.Config.StateModel>
@{
    ViewData["Title"] = "PopulateStateCollection";
    var message = ViewBag.Message;
    var collectionIsEmpty = ViewBag.EmptyCollection;
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
    <style>
        #sucess {
            color: green;
            text-align: end;
        }

        #fail {
            color: red;
            text-align: end;
        }

        .infoMessage {
            font-family: Arial, Helvetica, sans-serif;
            font-size: large;
            font-display: auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="subtitleDiv">
            <h2 id="ProcessDescription"> State Collection Info </h2>
        </div>

        @if (collectionIsEmpty.Equals("true"))
        {
            <p class="infoMessage" id="sucess"><strong>@message</strong></p>
        }
        @if (collectionIsEmpty.Equals("false"))
        {
            <p class="infoMessage" id="fail"><strong>@message</strong></p>
        }
    </div>
    <div class="container">
        <div class="table-responsive table-striped">
            <table class="table table-bordered" border="1" id="processResultTable">
                <thead>
                    <tr id="tableHeader">
                        <th>
                            @Html.DisplayName("State Order Number")
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Value)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 1; i <= Model.Count(); i++)
                    {
                        <tr id="tableBody">
                            <td>
                                #_@i
                            </td>
                            <td>
                                @Html.DisplayFor(modelIndex => Model.ElementAt(i - 1).Value)
                            </td>
                            <td>
                                @Html.DisplayFor(modelIndex => Model.ElementAt(i - 1).Description)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container">
        <button type="button" onclick="GoBack();"><i class="fa fa-toggle-left"> Go Back </i></button>
    </div>
</body>

DinamicDataMvc/Views/Tools/WebFormGenerator.cshtml
@*First web form test *@
@{
    ViewData["Title"] = "WebFormGenerator";

    string fragment1 = ViewBag.Fragment1;
    string fragment2 = ViewBag.Fragment2;
    string fragment3 = ViewBag.Fragment3;
    string fragment4 = ViewBag.Fragment4;
}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js"></script>
    <link rel="stylesheet" href="~/css/PageStyleFile.css" />
</head>

<body style="background-color:ghostwhite">
    @Html.Raw(fragment1)
    @Html.Raw("<br />")
    @Html.Raw(fragment2)
    @Html.Raw("<br />")
    @Html.Raw(fragment3)
    @Html.Raw("<br />")
    @Html.Raw(fragment4)
</body>