DinamicDataMvc/Controllers/ProcessDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DinamicDataMvc.Interfaces;
using DinamicDataMvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace DinamicDataMvc.Controllers
{
    public class ProcessDetailsController : Controller
    {
        private readonly IConnectionManagement _Connection;
        private readonly IGetProcessDetailsByName _Details;
        private readonly IGetBranchById _Branch;
        private readonly IGetDataById _Data;

        public ProcessDetailsController(IConnectionManagement Connection, IGetProcessDetailsByName Details, IGetBranchById Branch, IGetDataById Data)
        {
            _Connection = Connection;
            _Details = Details;
            _Branch = Branch;
            _Data = Data;
        }

        [HttpGet("/ProcessDetails/ByName/{id}")]
        public IActionResult ByName(string id)
        {
            if(id == null)
            {
                return BadRequest();
            }
            _Connection.DatabaseConnection();
            _Details.SetDatabase(_Connection.GetDatabase());
            _Branch.SetDatabase(_Connection.GetDatabase());

            _Details.ReadFromTable(id);
            List<MetadataModel> modelList = _Details.GetModels();
            List<ViewMetadataModel> viewModelList = new List<ViewMetadataModel>();

            ViewBag.Name = modelList[0].Name; //Stores the process name;

            foreach (var model in modelList)
            {
                _Branch.ReadFromDatabase(model.Branch);
                ViewMetadataModel _details = new ViewMetadataModel()
                {
                    Id = model.Id,
                    Name = model.Name,
                    Version = model.Version.ToString(),
                    Date = model.CreatedDate.ToShortDateString(),
                    Branch = _Branch.GetBranches(),
                    State = null,
                };
                viewModelList.Add(_details);
            }

            return View("ByName", viewModelList);
        }

        [HttpGet("/ProcessDetails/ByVersion/{id}")]
        public IActionResult ByVersion(string id)
        {
            //Se o valor do identificador, for nulo ou vazio, o controlador devolve o status: BadRequest() --> error 400; 
            if (String.IsNullOrEmpty(id))
            {
                return BadRequest();
            }

            string name = Request.Query["Name"];
            ViewBag.Name = name;

            //_VersionCode.SetNumber(id);
            int versionNumber = Convert.ToInt32(id);


            _Connection.DatabaseConnection(); //Estabeleçe-se a conexão com a base de dados;
            var _database = _Connection.GetDatabase(); //Obtêm-se a base de dados pretendida para trabalhar as coleções de dados;
            _Details.SetDatabase(_database); //A base de dados em contexto é passada ao serviço;
            _Details.ReadFromTable(name); //Obtem-se da tabela Metadata 
            List<MetadataModel> models = _Details.GetModels(); //Armazena os modelos retornados que satisfaçam a condição ter um nome igual ao recebido

            MetadataModel filteredModel = null;
            foreach(var model in models)
            {
                if (model.Version == versionNumber)
                {
                    filteredModel = model;
                }
            }

            _Branch.SetDatabase(_database);
            _Branch.ReadFromDatabase(filteredModel.Branch);


            List<DataProcessModel> DataModelsList = new List<DataProcessModel>();
           
            foreach(var itemId in filteredModel.Data)
            {
                _Data.SetDatabase(_database);
                _Data.ReadFromDatabase(itemId);
                DataProcessModel model = _Data.GetModel();
                DataModelsList.Add(model);
            }

            ViewBag.Data = DataModelsList;

            ViewMetadataModel filteredProcess = new ViewMetadataModel()
            {
                Id = filteredModel.Id,
                Name = filteredModel.Name,
                Version = filteredModel.Version.ToString(),
                Date = filteredModel.CreatedDate.ToString(),
                Branch = _Branch.GetBranches(),
                State = null
            };

            return View(filteredProcess);
        }

        [HttpGet("/ProcessDetails/Properties")]
        public IActionResult Properties()
        {
            string Id = Request.Query["ID"];
            _Data.SetDatabase(_Connection.GetDatabase());
            _Data.ReadFromDatabase(Id);
            return View(_Data.GetModel());
        }
    }
}

DinamicDataMvc/Controllers/ProcessMetadataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DinamicDataMvc.Interfaces;
using DinamicDataMvc.Models;
using Microsoft.AspNetCore.Mvc;
using PagedList.Core;

namespace DinamicDataMvc.Controllers
{
    public class ProcessMetadataController : Controller
    {
        private readonly IConnectionManagement _Connection;
        private readonly IGetProcessesMetadata _GetMetadata;
        private readonly IGetBranchById _GetBranchById;
        private readonly IGetStateById _GetStateById;

        public ProcessMetadataController(IConnectionManagement Connection, IGetProcessesMetadata GetMetadata, IGetBranchById GetBranchById, IGetStateById GetStateById)
        {
            _Connection = Connection;
            _GetMetadata = GetMetadata;
            _GetBranchById = GetBranchById;
            _GetStateById = GetStateById;
        }

        [HttpGet("/ProcessMetadata/GetProcessesMetadata")]
        public IActionResult GetProcessesMetadata(int page = 1, int pageSize = 1)
        {
            string name = null;
            int version = 0;

            //Verificações dos parâmetros recebidos no URL do pedido (nome e versão) do processo (Metadata)
            if (!Request.Query["SearchVersion"].Equals(""))
            {
                version = Convert.ToInt32(Request.Query["SearchVersion"]);
            }

            if (!Request.Query["SearchName"].Equals(""))
            {
                name = Request.Query["SearchName"];
            }

            _Connection.DatabaseConnection();
            _GetMetadata.SetDatabase(_Connection.GetDatabase()); //Estabeleçe a conexão;

            _GetMetadata.SetFilterParameters(name, version); //Definem-se parâmetros de filtragem de informação
            _GetMetadata.ReadFromDatababe(); //Procede-se à leitura da base de dados;

            _GetBranchById.SetDatabase(_Connection.GetDatabase());
            _GetStateById.SetDatabase(_Connection.GetDatabase());

            List<ViewMetadataModel> ListModel = new List<ViewMetadataModel>();
            List<MetadataModel> ListOfModels = _GetMetadata.GetProcessesMetadataList();

            foreach (var model in ListOfModels)
            {
                _GetBranchById.ReadFromDatabase(model.Branch);
                _GetStateById.ReadFromDatabase(model.State);

                ViewMetadataModel _model = new ViewMetadataModel()
                {
                    Name = model.Name,
                    Version = model.Version.ToString(),
                    Date = model.CreatedDate.ToShortDateString(),
                    Branch = _GetBranchById.GetBranches(),
                    State = _GetStateById.GetStateDescription()
                };
                ListModel.Add(_model);
            }

            PagedList<ViewMetadataModel> newModel = new PagedList<ViewMetadataModel>(ListModel.AsQueryable(), page, pageSize);
            return View(newModel);
        }

        [HttpGet("/ProcessMetadata/ProcessDetails/{id}")]
        public IActionResult ProcessDetails(string id)
        {
            return Redirect("~/ProcessDetails/Details/" + id);
        }
    }
}

DinamicDataMvc/Views/ProcessMetadata/GetProcessesMetadata.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, PagedList.Core.Mvc
@model PagedList.Core.PagedList<DinamicDataMvc.Models.ViewMetadataModel>
@{
    ViewData["Title"] = "TestMetadataList";
}
<section>
    <div class="text-body">
        <h4>Filters</h4>
    </div>
    @using (Html.BeginForm("Fake", "TestMetadataList", FormMethod.Get))
    {
        @await Html.PartialAsync("_Filter")
    }
</section>
<br />
<section>
    <div class="text-body">
        <h4>Metadata</h4>
    </div>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th valign="middle" align="center">
                        @Html.DisplayNameFor(model => model[0].Name)
                    </th>
                    <th valign="middle" align="center">
                        @Html.DisplayNameFor(model => model[0].Version)
                    </th>
                    <th valign="middle" align="center">
                        @Html.DisplayNameFor(model => model[0].Date)
                    </th>
                    <th valign="middle" align="center">
                        @Html.DisplayNameFor(model => model[0].Branch)
                    </th>
                    <th valign="middle" align="center">
                        @Html.DisplayNameFor(model => model[0].State)
                    </th>
                </tr>
            </thead>
            <tbody id="ProcessList">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(@Html.DisplayTextFor(modelItem => item.Name), "ByName", "ProcessDetails", new { ID = item.Name })
                        </td>
                        <td>
                            @Html.ActionLink(@Html.DisplayTextFor(modelItem => item.Version), "ByVersion", "ProcessDetails", new { ID = item.Version, Name = item.Name })
                        </td>
                        <td>
                            @Html.DisplayTextFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayTextFor(modelItem => item.Branch)
                        </td>
                        <td>
                            @Html.DisplayTextFor(modelItem => item.State)
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { /*ID = item.Id*/ })
                        </td>
                    </tr>
                }
            </tbody>
            <tr>
                <td colspan="3" align="left">
                    <pager list="@Model" asp-action="GetProcessesMetadata" asp-controller="ProcessMetadata"></pager>
                </td>
            </tr>
        </table>
    </div>
</section>

DinamicDataMvc/Views/ProcessMetadata/_Filter.cshtml
<div>
    <span>
        @Html.Label("Name")
        @Html.TextBox("SearchName", ViewBag.SearchName as string)
        @Html.Label("Version")
        @Html.DropDownList("SearchVersion", new SelectList(new List<string>() { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }), "Select Version", ViewBag.SearchVersion as string)
        <input type="submit" value="" style="background:url('/images/search_logo.png') no-repeat center; width:60px; height:40px; vertical-align:middle" />
    </span>
</div>